### ISSUE TITLE
Tests failing due to the ambiguity error for `\` with `PDMat` and `TrackedArray`

### ISSUE THREAD

**Issue by torfjelde** [TuringLang/Turing.jl#1358]
See logs: https://github.com/TuringLang/Turing.jl/pull/1357/checks?check_run_id=883458568.

Seems to be an issue with `\` being a bit "too" specialized in PDMats.jl. Uncertain where to raise the issue, so I've just raised it here and we can move it or bother someone else about it if that's the right course of action.

**Comment by mohamed82008** [comment]
I think changing `TrackedArray` in Tracker's method to `TrackedVecOrMat` should fix this.

**Comment by yebai** [comment]
Could we fix this from the Turing side first to get #1357 merged?

**Comment by torfjelde** [comment]
> I think changing TrackedArray in Tracker's method to TrackedVecOrMat should fix this.

Unfortunately it doesn't seem to do the trick :confused: 

```julia
PDMatDistribution AD: Error During Test at /home/tor/.julia/dev/Turing/test/core/ad.jl:284
  Got exception outside of a @test
  MethodError: \(::PDMat{Float64,Array{Float64,2}}, ::TrackedArray{…,Array{Float64,2}}) is ambiguous. Candidates:
    \(a::PDMat, x::Union{AbstractArray{T,1}, AbstractArray{T,2}} where T) in PDMats at /home/tor/.julia/packages/PDMats/8bndI/src/pdmat.jl:51
    \(A::AbstractArray, B::Union{TrackedArray{T,1,A}, TrackedArray{T,2,A}} where A where T) in Tracker at /home/tor/.julia/dev/Tracker/src/lib/array.jl:299
    \(A::AbstractArray{T,2} where T, B::Union{AbstractArray{T,1}, AbstractArray{T,2}} where T) in LinearAlgebra at /opt/julia-1.4.0/share/julia/stdlib/v1.4/LinearAlgebra/src/generic.jl:1103
  Possible fix, define
    \(::PDMat, ::Union{TrackedArray{T,1,A}, TrackedArray{T,2,A}} where A where T)
```
seems like the issue is that `A` is not specified. It also seems like a bug that is "recognized" (or at least they're aware that such issues could arise): https://github.com/FluxML/Tracker.jl/blob/b460dcf5199c7d64ec5ea9e2392fa131f7369b2e/src/lib/array.jl#L297

**Comment by devmotion** [comment]
I'm not sure if this can be fixed without defining `\(::PDMat, ::Union{TrackedArray{T,1,A}, TrackedArray{T,2,A}} where A where T)` explicitly (as already suggested by Julia in the initial error message): Generalizing the definition in PDMats to `\(a::PDMat, x::AbstractArray)` leads to test errors in PDMats since LinearAlgebra defines `\(A::AbstractArray{T,2} where T, B::Union{AbstractArray{T,1}, AbstractArray{T,2}} where T)`. Thus the definition for `AbstractVecOrMat` is needed in PDMats - but then I  don't see how one can avoid the method ambiguity by modifying the definitions in Tracker (without depending on PDMats and defining the missing dispatch explicitly). Maybe I'm missing something?

BTW all the issues (and also the test errors in DistributionsAD that we observe there suddenly) are due to PDMats 0.10 which introduced `AbstractPDMat <: AbstractMatrix`.

**Comment by torfjelde** [comment]
Hmm, so do we just introduce this particular overload into DistributionsAD.jl?

**Comment by devmotion** [comment]
I guess we could do that for now, but DistributionsAD requires some more fixes to be compatible with PDMats 0.10 that @nmheim is working on (I think?) (we have to resolve some method ambiguities for `Wishart`, `InverseWishart`, etc.). So I assume it will still take some more days until the issues are resolved completely and a new version of DistributionsAD could be released.

**Comment by mohamed82008** [comment]
I think I fixed that in https://github.com/TuringLang/DistributionsAD.jl/pull/97 conditional on https://github.com/TuringLang/DistributionsAD.jl/pull/97.

**Comment by devmotion** [comment]
That's not related I think? Or at least not enough: changes such as https://github.com/nmheim/DistributionsAD.jl/pull/1/commits/a8aa4521661404afb87f621d85dc9b68e0921f9a are needed.

**Comment by mohamed82008** [comment]
Let me re-run the tests locally. They passed before.

**Comment by nmheim** [comment]
The `Wishart`/`InverserWishart` tests for `Tracker` are fixed in nmheim/DistributionsAD.jl#1 , but the ones for `ReverseDiff` are still failling. They should be fixed by TuringLang/DistributionsAD.jl#97 though. So I guess we have to wait for the Distributions.jl issue to be merged...? I can move the changes I made on my fork to a different place if that is more convenient to organize.

**Comment by devmotion** [comment]
I'm not sure the other PR is needed? If it's actually the case, you could still open a PR with current changes in your branch - at least it fixes the Tracker issues.

**Comment by yebai** [comment]
Is this fixed now?

**Comment by devmotion** [comment]
No, but https://github.com/FluxML/Tracker.jl/pull/81 contains a fix.

**Comment by devmotion** [comment]
Tracker 0.2.11 was released and contains the fix, hence the ambiguity error is fixed on Turing master (see, e.g., https://github.com/TuringLang/Turing.jl/runs/986429368?check_suite_focus=true). However, since Tracker 0.2.11 is only compatible with Julia >= 1.3, older Julia versions still fail. IMO we should maybe drop support of Julia < 1.3 - alternatively, we would have to backport such bugfixes to older Julia versions, which would, e.g., mean to include a file with all (major) bugfixes from Tracker 0.2.8 to 0.2.11 for  these older Julia versions, but it's unclear to me how that could work in a reasonable way and without significantly increased developer burden (since the Tracker devs decided to drop support for these Julia versions).

**Comment by devmotion** [comment]
Fixed by dropping support for Julia < 1.3.
