### ISSUE TITLE
Zygote's compilation scales badly with the number of `~` statements

### ISSUE THREAD

**Issue by torfjelde** [TuringLang/Turing.jl#1754]
I'm not certain whether or not this can be considered a "Turing.jl-issue" or not, but I figured I would at least raise it as an issue here so people are aware.

The compilation time of Zygote scales quite badly with the number of `~` statements.

**TL;DR: it takes almost 5 minutes to compile a model with 14 `~` statements. I don't have the result here, but at some point I tried one with 20 `~` statements, and it took a full ~23 mins to compile.**

# Demo

```julia
using Turing, Zygote
```

```julia
Turing.setadbackend(:zygote);
adbackend = Turing.Core.ZygoteAD();
spl = DynamicPPL.SampleFromPrior();
```

```julia
results = []
num_tildes = 0
```

Running the following snippet a couple of times we get a sense of the compilation times:

```julia
num_tildes += 1

Zygote.refresh()

expr = :(function $(Symbol(:demo, num_tildes))() end) |> Base.remove_linenums!;
mainbody = last(expr.args);
append!(mainbody.args, [:($(Symbol("x", j)) ~ Normal()) for j = 1:num_tildes]);

f = @eval $(DynamicPPL.model(:Main, LineNumberNode(1), expr, false))
model = f();
vi = DynamicPPL.VarInfo(model);

t = @elapsed Turing.Core.gradient_logp(
   adbackend,
   vi[spl],
   vi,
   model,
   spl
);
push!(results, t)
```

```julia
results
```

    14-element Vector{Any}:
      15.917412882
       9.600213651
      14.911253238
      24.699050206
      71.811476745
      49.158314248
      46.059394601
      57.44494627
      75.514564551
      94.927956369
     134.165383535
     156.079943416
     202.745837585
     273.93479382

That is, **it takes almost 5 minutes to compile a model with 14 `~` statements. I don't have the result here, but at some point I tried one with 20 `~` statements, and it took a full ~23 mins to compile.**

## Additional info

```julia
versioninfo()
```

    Julia Version 1.6.2
    Commit 1b93d53fc4 (2021-07-14 15:36 UTC)
    Platform Info:
      OS: Linux (x86_64-pc-linux-gnu)
      CPU: Intel(R) Core(TM) i7-10710U CPU @ 1.10GHz
      WORD_SIZE: 64
      LIBM: libopenlibm
      LLVM: libLLVM-11.0.1 (ORCJIT, skylake)

```julia
Pkg.status()
```

        Status `/tmp/jl_PHYdgF/Project.toml`
    [fce5fe82] Turing v0.19.2
    [e88e6eb3] Zygote v0.6.32

**Comment by wupeifan** [comment]
Thanks a lot for posting this!

**Comment by ParadaCarleton** [comment]
Do we have code that checks the compile times of models? How long has Zygote compilation been taking this long?

**Comment by wupeifan** [comment]
>How long has Zygote compilation been taking this long?

Since Julia 1.6 afaik.

**Comment by ParadaCarleton** [comment]
> > How long has Zygote compilation been taking this long?
> 
> Since Julia 1.6 afaik.

As in, the 1.6 update caused it? Is the compilation faster on 1.5?

**Comment by jlperla** [comment]
@torfjelde probably can get the right answer, if it matters. There are a lot of packages and versions interacting so not sure it necessarily matches a particular Julia version. It might take just as long to find the exact combination of Julia, zygote, chainrules, Turing, dynamicppl, etc versions that caused it as it would to actually solve the problem.

**Comment by wupeifan** [comment]
> As in, the 1.6 update caused it? Is the compilation faster on 1.5?

I don't think so. It's only my experience instead of any benchmarking/profiling (which we need!) I don't have a good answer to this question.

**Comment by jlperla** [comment]
Sorry to bump so soon @torfjelde   but we have any sense of a timeline on this?  Are we thinking a week, a month, etc.? We would help out but I fear this is a little too tightly connected to the PPL macros for us to contribute to.

**Comment by torfjelde** [comment]
I'm sorry, I can't put a timeline on this right now. 

And I worry and suspect it's not particularly related to Turing, unfortunately :confused: There was one change we made in Turing that I worried could have caused it, but when I tried with an older version the performance was still horrible.

The best way to identify what's wrong is to just run the test above for different versions of Turing and Zygote.

**Comment by torfjelde** [comment]
As of right now I have the following results:

| Julia | Turing | Zygote | 1            | 5            | 10            | 15            |
|-------|--------|--------|--------------|--------------|---------------|---------------|
| 1.6.1 | 0.19   | 0.6    | 16.387332656 | 89.504752487 | 101.654405869 | 320.501781565 |
| 1.6.1 | 0.18   | 0.6    | 15.740250148 | 72.75134579  | 92.373805461  | 310.690419646 |
| 1.6.1 | 0.16   | 0.6    | 14.098175146 | 77.075566728 | 86.093118485  | 310.681374129 |
| 1.6.1 | 0.15   | 0.6    | 13.674902932 | 75.142343745 | 83.177268954  | 309.479831351 |
| 1.6.1 | 0.19.3 | 0.6.32 | 16.519126809 | 76.212964076 | 102.056456525 | 331.835923261 |
| 1.6.1 | 0.19.3 | 0.6.30 | 16.416369038 | 73.552713013 | 98.009949908  | 325.177503251 |
| 1.6.1 | 0.19.3 | 0.6.28 | 15.907693813 | 73.859609986 | 99.65385215   | 320.406822231 |
| 1.6.1 | 0.19.3 | 0.6.25 | 16.155023105 | 78.113216025 | 91.386990818  | 323.182170592 |
| 1.6.1 | 0.19.3 | 0.6.20 | 16.18978755  | 76.922928732 | 92.863883057  | 329.472662078 |
| 1.6.1 | 0.19.3 | 0.6.17 | 16.674484174 | 45.536406584 | 91.975029367  | 324.107966298 |
| 1.6.1 | 0.19.3 | 0.6.15 | 16.647893857 | 77.246173583 | 92.547574565  | 325.843565657 |

Columns with numeric values represents the number of `~` statements.

This is on the following system:
```julia
julia> versioninfo()
Julia Version 1.6.1
Commit 6aaedecc44 (2021-04-23 05:59 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-6850K CPU @ 3.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, broadwell)
```

**The sad news is that I can't really glean anything useful from the above :confused: Here it seems to be "fine" (taking 5mins to compile is not good, but it's much better than the reported numbers).**

Comments:
- When I tried running this benchmark on my laptop (which has 32G memory), Zygote earlier than 0.6.17 blew up (on Julia 1.6.3), i.e. it seems as if the memory-usage of Zygote changed significantly from 0.6.17 to 0.6.18?
- The version columns which are missing patch-version, e.g. `0.19`, are using the most recent version of Zygote which is compatible with the corresponding Turing-version. I can find these out if need be (the numbers are from an earlier version of the script I'm using).

`[2022-01-10 Mon 00:36]`: I'm now running the same benchmarks on Julia 1.6.5 just to make sure it has nothing to do with weird interactions between the particular Julia version and Zygote.

<details>
<summary> Script I'm running </summary>

```julia
using Pkg; Pkg.activate(mktempdir())
TURING_VERSION = ENV["TURING_VERSION"]
ZYGOTE_VERSION = ENV["ZYGOTE_VERSION"]

@info "Trying to install Turing@$(TURING_VERSION) and Zygote@$(ZYGOTE_VERSION)"
Pkg.add(name="Turing", version=TURING_VERSION)
Pkg.add(name="Zygote", version=ZYGOTE_VERSION)

using Turing, Zygote

pkgversion(mod) = Pkg.TOML.parsefile(joinpath(dirname(Pkg.project().path), "Manifest.toml"))[string(mod)][1]["version"]
@info "Installed Turing@$(pkgversion(Turing)) and Zygote@$(pkgversion(Zygote))"

Turing.setadbackend(:zygote);
adbackend = Turing.Core.ZygoteAD();
spl = DynamicPPL.SampleFromPrior();

results = []

num_tildes = 1
@info "Running" num_tildes
Zygote.refresh()

expr = :(function $(Symbol(:demo, num_tildes))() end) |> Base.remove_linenums!;
mainbody = last(expr.args);
append!(mainbody.args, [:($(Symbol("x", j)) ~ Normal()) for j = 1:num_tildes]);

f = @eval $(DynamicPPL.model(:Main, LineNumberNode(1), expr, false))
model = f();
vi = DynamicPPL.VarInfo(model);

t = @elapsed Turing.Core.gradient_logp(
   adbackend,
   vi[spl],
   vi,
   model,
   spl
);
push!(results, t)
@info "Result" t

num_tildes = 5
@info "Running" num_tildes
Zygote.refresh()

expr = :(function $(Symbol(:demo, num_tildes))() end) |> Base.remove_linenums!;
mainbody = last(expr.args);
append!(mainbody.args, [:($(Symbol("x", j)) ~ Normal()) for j = 1:num_tildes]);

f = @eval $(DynamicPPL.model(:Main, LineNumberNode(1), expr, false))
model = f();
vi = DynamicPPL.VarInfo(model);

t = @elapsed Turing.Core.gradient_logp(
   adbackend,
   vi[spl],
   vi,
   model,
   spl
);
push!(results, t)
@info "Result" t

num_tildes = 10
@info "Running" num_tildes
Zygote.refresh()

expr = :(function $(Symbol(:demo, num_tildes))() end) |> Base.remove_linenums!;
mainbody = last(expr.args);
append!(mainbody.args, [:($(Symbol("x", j)) ~ Normal()) for j = 1:num_tildes]);

f = @eval $(DynamicPPL.model(:Main, LineNumberNode(1), expr, false))
model = f();
vi = DynamicPPL.VarInfo(model);

t = @elapsed Turing.Core.gradient_logp(
   adbackend,
   vi[spl],
   vi,
   model,
   spl
);
push!(results, t)
@info "Result" t

num_tildes = 15
@info "Running" num_tildes
Zygote.refresh()

expr = :(function $(Symbol(:demo, num_tildes))() end) |> Base.remove_linenums!;
mainbody = last(expr.args);
append!(mainbody.args, [:($(Symbol("x", j)) ~ Normal()) for j = 1:num_tildes]);

f = @eval $(DynamicPPL.model(:Main, LineNumberNode(1), expr, false))
model = f();
vi = DynamicPPL.VarInfo(model);

t = @elapsed Turing.Core.gradient_logp(
   adbackend,
   vi[spl],
   vi,
   model,
   spl
);
push!(results, t)
@info "Result" t

println(join(results, " | "))

if haskey(ENV, "OUTPUT_FILE")
    open(ENV["OUTPUT_FILE"], "a") do io
        write(io, "| ", join([VERSION; pkgversion(Turing); pkgversion(Zygote); results;], " | "), " |")
        write(io, "\n")
    end
end
```

</details>

**Comment by jlperla** [comment]
Thanks @torfjelde 

Is there any chance this stuff gets better on 1.7 with the latest zygote? I know Turing doesn't support it yet, but does the dynamicppl let you test on 1.7?

**Comment by torfjelde** [comment]
> Is there any chance this stuff gets better on 1.7 with the latest zygote? I know Turing doesn't support it yet, but does the dynamicppl let you test on 1.7?

I _can_ but it will take a bit of work (currently using Turing functionality to compute the gradient).

Do you know _when_ you started experiencing these issues btw?

Also, maybe some of the Zygote people have any idea what's going on here @mcabbott ? TL;DR: Compilation time of `Zygote.gradient` blows up wrt. number of `~` in a Turing model.

**Comment by torfjelde** [comment]
Possibly related: https://github.com/FluxML/Zygote.jl/issues/1119

**Comment by torfjelde** [comment]
_Wow_, the `-O1` _really_ helps. See the results in the comment above.

**Comment by jlperla** [comment]
@torfjelde  Am I reading that correctly that Julia 1.6.5 + Turing 0.19.3 + Zygote 0.6.33  brings it back to sanity?

**Comment by torfjelde** [comment]
> Am I reading that correctly that Julia 1.6.5 + Turing 0.19.3 + Zygote 0.6.33 brings it back to sanity?

No, specifically you need the `-O1` optimization flag (the default is `-O3`). It seems as if Zygote + Julia 1.6 leads to some insane compilation times when the default optimizations are used.

**Comment by mcabbott** [comment]
See if https://github.com/FluxML/Zygote.jl/pull/1147 works as well as `-01` for this purpose. If you have any other benchmarks of runtime performance (i.e. `@btime`) it would also be interesting to see if those get worse.

**Comment by wupeifan** [comment]
I can confirm that `-O1` helps with our original problem by **significantly** decreasing the compilation time. Previously we have to wait for around 30-40min, and now it takes 2-3 Chopin preludes -- around 6min -- to compile. I would say this is similar to what I had in Julia 1.5.
Now the question is whether `-O1` generates much less efficient code than `-O3`.

**Comment by torfjelde** [comment]
> See if [FluxML/Zygote.jl#1147](https://github.com/FluxML/Zygote.jl/pull/1147) works as well as `-O1` for this purpose. If you have any other benchmarks of runtime performance (i.e. `@btime`) it would also be interesting to see if those get worse.

Will give it a go :+1: 

Btw, not sure if this is more useful information , but when I try `Zygote@0.6.25` even with `-O1` the runtime blows up again (the nearest more recent version I tried which had reasonable compile time was 0.6.28).

**Comment by ToucheSir** [comment]
I've never heard of Chopin preludes being used as a unit of measurement, but people should do that more often :)


> Now the question is whether `-O1` generates much less efficient code than `-O3`.

Betting on no, as most performance-sensitive stuff is gated behind a rule. _Maybe_ scalar- or control flow-heavy code, though the generated pullbacks for the latter are likely type unstable anyhow.

> but when I try `Zygote@0.6.25` even with `-O1` the runtime blows up again

Fixed by https://github.com/FluxML/Zygote.jl/pull/909 perhaps? That was in 0.6.27.

**Comment by torfjelde** [comment]
> See if [FluxML/Zygote.jl#1147](https://github.com/FluxML/Zygote.jl/pull/1147) works as well as `-O1` for this purpose. If you have any other benchmarks of runtime performance (i.e. `@btime`) it would also be interesting to see if those get worse.

Gave it a try; seems to do the trick! Benchmarks in table above.

Don't know what effect it has on performance though, but seems like it would be worth it.

**Comment by torfjelde** [comment]
> Fixed by FluxML/Zygote.jl#909 perhaps? That was in 0.6.27.

Ah, probably! I'll give it a go.

**Comment by jlperla** [comment]
Any progress on this issue by chance?  Did a check with Julia 1.7 and the latest Turing, DynamicPPL, and Zygote and am still getting > 30 minute TTFG for my model with 20ish parameters.  `-O1` makes things more reasonable, as it did before.

Just want to make sure that everyone knows those two Zygote issues linked did not fix things.

**Comment by ToucheSir** [comment]
Unfortunately I have nothing concrete to report, but I have been looking into this over the past couple of months. Any help on grokking compilation latency + Zygote's internals would be much appreciated. I can't speak for Keno, but to my knowledge working on this is not on anyone else's plate.

**Comment by ToucheSir** [comment]
@torfjelde I'm not able to repro your latest timings on 1.8.2 locally with the following reduced MWE:
```julia
using Turing, Zygote
using Turing: LogDensityProblems
using SnoopCompileCore

# This helps a bit, ~4s
# @eval Turing.DynamicPPL begin
#   ChainRulesCore.@non_differentiable is_flagged(::VarInfo, ::VarName, ::String)
# end

Turing.setadbackend(:zygote);
adbackend = Turing.Core.ZygoteAD();
spl = DynamicPPL.SampleFromPrior();

num_tildes = 5
# num_tildes = 10

expr = :(function $(Symbol(:demo, num_tildes))() end) |> Base.remove_linenums!;
mainbody = last(expr.args);
append!(mainbody.args, [:($(Symbol("x", j)) ~ Normal()) for j = 1:num_tildes]);

f = @eval $(DynamicPPL.model(:Main, LineNumberNode(1), expr, false))
model = f();
vi = DynamicPPL.VarInfo(model);

@info "starting eval"
ℓ = Turing.LogDensityFunction(vi, model, spl, DynamicPPL.DefaultContext());
ℓ_with_grad = LogDensityProblems.ADgradient(:Zygote, ℓ);
tinf = @snoopi_deep LogDensityProblems.logdensity_and_gradient(ℓ_with_grad, vi[spl]);
@info "done eval"

using SnoopCompile, ProfileView
@show tinf
```
Results:
```
# v0.6.49
tinf = InferenceTimingNode: 38.138395/69.026222 on Core.Compiler.Timings.ROOT() with 388 direct children
# https://github.com/FluxML/Zygote.jl/pull/1195
tinf = InferenceTimingNode: 37.486037/65.298454 on Core.Compiler.Timings.ROOT() with 423 direct children
```
Versioninfo:
```
Julia Version 1.8.2
Commit 36034abf260 (2022-09-29 15:21 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 8 × Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, haswell)
  Threads: 1 on 8 virtual cores
```

**Comment by ToucheSir** [comment]
I had a crack at figuring out _why_ inference times also scale so badly. All outputs of that exploration may be found in [this gist](https://gist.github.com/ToucheSir/d11c8a2a209481a0d61bf5898155e6ae).

It turns out that we can capture a good chunk of the slowness and poor scaling with just `pullback(model.f, ...)`. SnoopCompile didn't feel very helpful because it just reports high exclusive inference time for that function, but digging into the IR with SnoopCompile's Cthulhu integration did turn up something interesting.

To demonstrate, we should first examine `@code_warntype` output for the [un-transformed function](https://gist.github.com/ToucheSir/d11c8a2a209481a0d61bf5898155e6ae#file-forward_codeinfo-txt). DynamicPPL does generate a decent amount of code, but the compiler should be able to manage 600ish statements and 100ish slots[^1] without too much trouble.

Now let's see the output for the [augmented primal function](https://gist.github.com/ToucheSir/d11c8a2a209481a0d61bf5898155e6ae#file-primal_codeinfo-txt) from `pullback`. Yes, you read that correctly. Zygote generates a function with over 4,300 statements and over _19,000_ slots! I have no idea why both numbers are so high, but I suspect there is something up with the IRTools IR -> Julia IR translation that happens in Zygote[^2].

So what is to be done? The first thing that comes to mind is to figure out why this is happening on the IRTools side, and how much Zygote's own passes might be responsible. That however would require someone quite familiar with IRTools internals. The more ambitious plan would be to ditch IRTools in Zygote completely and use `CodeInfo`/`IRCode` like other libraries (including TuringLang's own [LibTask](https://github.com/TuringLang/Libtask.jl/issues/117)) have done. Having given this a try some months back, I think the biggest missing piece is someone who understands Zygote's pre-IRTools AD transform (or the implementing AD transforms on SSA IR in general) well enough to do the port. It's not clear how a lot of the logic in Zygote now would look if passes went from working on block args to Phi nodes, for example. 

[^1]: I count slots because someone mentioned before that they can consume quite a bit of memory during compilation. So having too many of them in a function may be the culprit behind the memory blowup documented here and in https://github.com/TuringLang/Turing.jl/issues/1754#issuecomment-1008460319.
[^2]: Zygote used to operate on native Julia IR, but switched to IRTools a couple of years back. This means every function goes through a native IR (really `CodeInfo`) -> IRTools IR -> AD transform -> native IR pipeline.

**Comment by yebai** [comment]
`Diffractor` will hopefully fix these issues, right?

**Comment by ToucheSir** [comment]
Last I asked there were no plans to support `setfield!` or `setindex!` on Dicts, both of which Turing seems to need. So I'm not terribly optimistic...

**Comment by ParadaCarleton** [comment]
Briefly going to comment on this to say--the solution to this issue is to use ReverseDiff or ForwardDiff.jl or (a few years down the line when it's mature) maybe some other autodiff solution like Enzyme.jl. Development on Zygote/IRTools and source-to-source AD in Julia (rather than LLVM) is effectively dead now.

**Comment by devmotion** [comment]
To be honest, ReverseDiff has other issues and ForwardDiff is not always an option. Actually, Zygote is developed much more actively (https://github.com/FluxML/Zygote.jl/commits/master) than ReverseDiff (https://github.com/JuliaDiff/ReverseDiff.jl/commits/master) or ForwardDiff (https://github.com/JuliaDiff/ForwardDiff.jl/commits/master) (there hasn't been any new release of master since the breaking change that downstream packages did - IMO correctly - reject in a non-breaking release was reapplied to the master branch; and nobody wants to deal with and possibly fix these still existing downstream issues, hence nobody is willing to tag any new release on the ForwardDiff master branch).

**Comment by ToucheSir** [comment]
> Actually, Zygote is developed much more actively (https://github.com/FluxML/Zygote.jl/commits/master) than ReverseDiff (https://github.com/JuliaDiff/ReverseDiff.jl/commits/master) or ForwardDiff (https://github.com/JuliaDiff/ForwardDiff.jl/commits/master)

Although this is true, it's not quite an apples-to-apples comparison because of what those commits are doing. The majority of Zygote work these days is maintenance work, and much of that is mandatory because some change in Julia internals broke the source-to-source AD bit. The rest are primarily filling in holes/edge cases/robustness issues in the existing rule system, which has many, many more of them than either Forward or ReverseDiff.

> To be honest, ReverseDiff has other issues...

IMO they should be listed out, because my impression is that many of them are more tractable than the fundamental ones facing Zygote. Some offline experimentation suggests that even the infamous lack of GPU support could be addressed without a complete package rewrite. That said, my personal deal-breaker with ReverseDiff is not any technical issue&mdash;it's that there appears to be no appetite for anything other than the most urgent maintenance. I can absolutely appreciate why this is the case, but it is a little disheartening to treat ReverseDiff as some technological dead-end when other languages/libraries have managed to take similar ideas further.

**Comment by thorek1** [comment]
any update on this? 
I am stuck with 36 `~` statements and didnt see the end of the compilation yet (Julia 1.10.1, Zygote 0.6.69, Turing 0.30.5) 
what are feasible workarounds? does `filldist` help?

**Comment by thorek1** [comment]
ok thanks for the info.

what i found to work reasonably well is wrapping all distributions in an arraydist.

for example (ignore the 4 element inputs and ` μσ`; i wrote my own wrappers):

```julia
# Handling distributions with varying parameters using arraydist
dists = [
InverseGamma(0.1, 2.0, 0.01, 3.0, μσ = true), # z_ea
InverseGamma(0.1, 2.0, 0.025,5.0, μσ = true), # z_eb
InverseGamma(0.1, 2.0, 0.01, 3.0, μσ = true), # z_eg
InverseGamma(0.1, 2.0, 0.01, 3.0, μσ = true), # z_eqs
InverseGamma(0.1, 2.0, 0.01, 3.0, μσ = true), # z_em
InverseGamma(0.1, 2.0, 0.01, 3.0, μσ = true), # z_epinf
InverseGamma(0.1, 2.0, 0.01, 3.0, μσ = true), # z_ew
Beta(0.5, 0.20, μσ = true), # crhoa
Beta(0.5, 0.20, μσ = true), # crhob
Beta(0.5, 0.20, μσ = true), # crhog
Beta(0.5, 0.20, μσ = true), # crhoqs
Beta(0.5, 0.20, μσ = true), # crhoms
Beta(0.5, 0.20, μσ = true), # crhopinf
Beta(0.5, 0.20, μσ = true), # crhow
Beta(0.5, 0.2, μσ = true), # cmap
Beta(0.5, 0.2, μσ = true), # cmaw
Normal(4.0, 1.5,   2.0, 15.0), # csadjcost
Normal(1.50,0.375, 0.25, 3.0), # csigma
Beta(0.7, 0.1, μσ = true), # chabb
Beta(0.5, 0.1, μσ = true), # cprobw
Normal(2.0, 0.75, 0.25, 10.0), # csigl
Beta(0.5, 0.10, μσ = true), # cprobp
Beta(0.5, 0.15, μσ = true), # cindw
Beta(0.5, 0.15, μσ = true), # cindp
Beta(0.5, 0.15, μσ = true), # czcap
Normal(1.25, 0.125, 1.0, 3.0), # cfc
Normal(1.5, 0.25, 1.0, 3.0), # crpi
Beta(0.75, 0.10, μσ = true), # crr
Normal(0.125, 0.05, 0.001, 0.5), # cry
Normal(0.125, 0.05, 0.001, 0.5), # crdy
Gamma(0.625, 0.1, 0.1, 2.0, μσ = true), # constepinf
Gamma(0.25, 0.1, 0.01, 2.0, μσ = true), # constebeta
Normal(0.0, 2.0, -10.0, 10.0), # constelab
Normal(0.4, 0.10, 0.1, 0.8), # ctrend
Normal(0.5, 0.25, 0.01, 2.0), # cgy
Normal(0.3, 0.05, 0.01, 1.0), # calfa
]

Turing.@model function model_loglikelihood_function(data, m, observables,fixed_parameters)
    all_params ~ Turing.arraydist(dists)

    z_ea, z_eb, z_eg, z_eqs, z_em, z_epinf, z_ew, crhoa, crhob, crhog, crhoqs, crhoms, crhopinf, crhow, cmap, cmaw, csadjcost, csigma, chabb, cprobw, csigl, cprobp, cindw, cindp, czcap, cfc, crpi, crr, cry, crdy, constepinf, constebeta, constelab, ctrend, cgy, calfa = all_params

...
end
```

**Comment by marcobonici** [comment]
@thorek1 thanks for sharing this!
I will try this later but could you please share how much did this improve the compilation time?
Thx in advance!

**Comment by wupeifan** [comment]
Oh I must just saw another one trying to estimate Smets & Wouters paper with NUTS in Julia...
I think with that amount of `~` things are still tolerable... 36 should be fine though, at least when I raised the issue it was for a second-order Smets&Wouters...
